// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventsHooks struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Input                []byte   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Response             []byte   `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsHooks) Reset()         { *m = EventsHooks{} }
func (m *EventsHooks) String() string { return proto.CompactTextString(m) }
func (*EventsHooks) ProtoMessage()    {}
func (*EventsHooks) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *EventsHooks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsHooks.Unmarshal(m, b)
}
func (m *EventsHooks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsHooks.Marshal(b, m, deterministic)
}
func (m *EventsHooks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsHooks.Merge(m, src)
}
func (m *EventsHooks) XXX_Size() int {
	return xxx_messageInfo_EventsHooks.Size(m)
}
func (m *EventsHooks) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsHooks.DiscardUnknown(m)
}

var xxx_messageInfo_EventsHooks proto.InternalMessageInfo

func (m *EventsHooks) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EventsHooks) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *EventsHooks) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*EventsHooks)(nil), "EventsHooks")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe5, 0xe2, 0x76, 0x2d, 0x4b, 0xcd, 0x2b,
	0x29, 0xf6, 0xc8, 0xcf, 0xcf, 0x2e, 0x16, 0x12, 0xe1, 0x62, 0x4d, 0x05, 0x71, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x90, 0x68, 0x66, 0x5e, 0x41, 0x69, 0x89, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x4f, 0x10, 0x84, 0x23, 0x24, 0xc5, 0xc5, 0x51, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57,
	0x9c, 0x2a, 0xc1, 0x0c, 0x96, 0x80, 0xf3, 0x8d, 0x4c, 0xb9, 0x78, 0x83, 0x53, 0x13, 0x8b, 0x92,
	0x33, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x54, 0xb8, 0xd8, 0x20, 0x02, 0x42, 0x3c,
	0x7a, 0x48, 0x16, 0x4a, 0xa1, 0xf0, 0x92, 0xd8, 0xc0, 0x8e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xf6, 0xe3, 0x23, 0x88, 0xa3, 0x00, 0x00, 0x00,
}
